include Rules.make

.PHONY:	all clean help resource_install trafficlights trafficlights_clean trafficlights_install dcmotor dcmotor_clean dcmotor_install samotor samotor_clean samotor_install buzzer buzzer_clean buzzer_install keypad keypad_clean keypad_install ad ad_clean ad_install da da_clean da_install lcd lcd_clean lcd_install

#==============================================================================
# Default build target
#==============================================================================
default: all

#==============================================================================
# Clean up the targets built by 'make all'.
#==============================================================================
clean: trafficlights_clean dcmotor_clean samotor_clean buzzer_clean keypad_clean ad_clean da_clean lcd_clean

#==============================================================================
# Build everything rebuildable.
#==============================================================================
all: trafficlights dcmotor samotor buzzer keypad ad da lcd

#==============================================================================
# Install everything
#==============================================================================
install: resource_install trafficlights_install dcmotor_install samotor_install buzzer_install keypad_install ad_install da_install lcd_install

#==============================================================================
# A help message target.
#==============================================================================
help:
	@echo
	@echo "Available build targets are:"
	@echo
	@echo "  ctr                 : Build all base components (See Note below)" 
	@echo
	@echo "  all                        : Builds all components and applications/examples"
	@echo "  clean                      : Remove files generated by the 'all' target"
	@echo
	@echo "  install                    : Install all the targets in $(EXEC_DIR)"
	@echo
	@echo "  resource_install           : Install the resources in $(EXEC_DIR)"
	@echo
	@echo "  trafficlights              : Build the traffic lights module"
	@echo "  trafficlights_clean        : Remove generated traffic lights files."
	@echo "  trafficlights_install      : Install traffic lights module"
	@echo
	@echo "  dcmotor                    : Build the dcmotor module"
	@echo "  dcmotor_clean              : Remove generated dcmotor files."
	@echo "  dcmotor_install            : Install dcmotor module"
	@echo
	@echo "  samotor                    : Build the samotor module"
	@echo "  samotor_clean              : Remove generated samotor files."
	@echo "  samotor_install            : Install samotor module"
	@echo
	@echo "  buzzer                     : Build the buzzer module"
	@echo "  buzzer_clean               : Remove generated buzzer files."
	@echo "  buzzer_install             : Install buzzer module"
	@echo
	@echo "  keypad                     : Build the keypad module"
	@echo "  keypad_clean               : Remove generated keypad files."
	@echo "  keypad_install             : Install keypad module"
	@echo
	@echo "  ad                         : Build the ad module"
	@echo "  ad_clean                   : Remove generated ad files."
	@echo "  ad_install                 : Install ad module"
	@echo
	@echo "  da                         : Build the da module"
	@echo "  da_clean                   : Remove generated da files."
	@echo "  da_install                 : Install da module"
	@echo
	@echo "  lcd                         : Build the lcd module"
	@echo "  lcd_clean                   : Remove generated lcd files."
	@echo "  lcd_install                 : Install lcd module"

	@echo
################################################################################
# install resources
################################################################################
resource_install:
	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar html $(EXEC_DIR)/usr/share/matrix/

	install -d $(EXEC_DIR)/usr/share/matrix/images
	cp -ar images/ctr-icon.png $(EXEC_DIR)/usr/share/matrix/images/


################################################################################
# Build traffic lights examples
################################################################################
trafficlights:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd trafficlights ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

trafficlights_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd trafficlights ; qmake ; $(MAKE)  distclean

trafficlights_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 trafficlights/trafficlights $(EXEC_DIR)/home/root/ctr/

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/traffic.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/traffic-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build dcmotor examples
################################################################################
dcmotor:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd dcmotor ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

dcmotor_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd dcmotor ; qmake ; $(MAKE)  distclean

dcmotor_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 dcmotor/dcmotor $(EXEC_DIR)/home/root/ctr/

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/dcmotor.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/dcmotor-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build samotor examples
################################################################################
samotor:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd samotor ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

samotor_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd samotor ; qmake ; $(MAKE)  distclean

samotor_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 samotor/samotor $(EXEC_DIR)/home/root/ctr/

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/samotor.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/samotor-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build buzzer examples
################################################################################
buzzer:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd buzzer ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

buzzer_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd buzzer ; qmake ; $(MAKE)  distclean

buzzer_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 buzzer/buzzer $(EXEC_DIR)/home/root/ctr/
	cp -ar buzzer/images $(EXEC_DIR)/home/root/ctr/
	cp buzzer/buzzer.cfg $(EXEC_DIR)/home/root/ctr/buzzer.cfg

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/buzzer.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/buzzer-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build keypad examples
################################################################################
keypad:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd keypad ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

keypad_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd keypad ; qmake ; $(MAKE)  distclean

keypad_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 keypad/keypad $(EXEC_DIR)/home/root/ctr/
	cp images/1.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/2.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/3.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/4.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/5.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/6.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/7.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/8.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/9.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y1.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y2.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y3.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y4.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y5.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y6.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y7.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y8.png $(EXEC_DIR)/home/root/ctr/images/
	cp images/y9.png $(EXEC_DIR)/home/root/ctr/images/
	cp keypad/keypad.cfg $(EXEC_DIR)/home/root/ctr/keypad.cfg

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/keypad.bin $(EXEC_DIR)/home/root/ctr/data/
	install -m 0755 lcd/data/key-*.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/keypad-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build ad examples
################################################################################
ad:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd ad ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

ad_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd ad ; qmake ; $(MAKE)  distclean

ad_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 ad/ad $(EXEC_DIR)/home/root/ctr/

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/ad.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/ad-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build ad examples
################################################################################
da:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd da ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

da_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd da ; qmake ; $(MAKE)  distclean

da_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 da/da $(EXEC_DIR)/home/root/ctr/

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/da.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/da-icon.png $(EXEC_DIR)/usr/share/matrix/images/

################################################################################
# Build lcd examples
################################################################################
lcd:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup ; cd lcd ; qmake ; $(MAKE) PLATFORM=$(PLATFORM)

lcd_clean:
	. $(SDK_INSTALL_DIR)/linux-devkit/environment-setup;  cd lcd ; qmake ; $(MAKE)  distclean

lcd_install:
	install -d $(EXEC_DIR)/home/root/ctr
	install -m 0755 lcd/lcd $(EXEC_DIR)/home/root/ctr/

	install -d $(EXEC_DIR)/home/root/ctr/data
	install -m 0755 lcd/data/welcome.bin $(EXEC_DIR)/home/root/ctr/data/

	install -d $(EXEC_DIR)/usr/share/matrix
	cp -ar images/lcd-icon.png $(EXEC_DIR)/usr/share/matrix/images/
